### ISSUE TITLE
NPE after registration

### ISSUE THREAD

**Issue by k-gregory** [k-gregory/registry#1]
Backend fails with NullPointerException after registration.
Steps to reproduce:
- Open https://gregory-k.me/register in private mode (with no session)
- Enter new username and password, press register

**Comment by kostya9** [comment]
@k-gregory please document such abbreviations (NPE) in the wiki if you are going to proactively use them

**Comment by k-gregory** [comment]
@kostya9 now wiki contains the [glossary](https://github.com/k-gregory/registry/wiki/Glossary) page. However, NPE abbreviation is widely used among Java developers, for example see [Spring issues with NPE](https://jira.spring.io/secure/QuickSearch.jspa?searchString=NPE)

**Comment by kostya9** [comment]
@k-gregory thank you, seems like I am not experienced enough in Java development
