### ISSUE TITLE
Deployment fails with 'Out of memory'

### ISSUE THREAD

**Issue by k-gregory** [k-gregory/registry#13]
Deployment fails due to lack of memory

**Comment by kostya9** [comment]
@k-gregory Will we build the production frontend bundle in Travis build box or are we investigating other options?

**Comment by k-gregory** [comment]
I think building in Travis build box is good enough solution

**Comment by k-gregory** [comment]
Fixed in 01b30e48ae52561f286e7e3a33dbb72870953de6

**Comment by k-gregory** [comment]
Fixed in 01b30e48ae52561f286e7e3a33dbb72870953de6
