### ISSUE TITLE
Admin page with users list and user creation process

### ISSUE THREAD

**Issue by kostya9** [k-gregory/registry#18]
- list of users with an ability to see the details of them
- page or modal to create a user
- creation of the user sends them an email (? open for discussion ?)
- abilty to assign roles (what roles?)

**Comment by k-gregory** [comment]
>creation of the user sends them an email

Can this be needed in government agency?

**Comment by kostya9** [comment]
@k-gregory if I were an employee, assigned to the agency, it would be nice to engage in work as soon as the account is created. However, I suppose, that will also be communicated through his supervisor. 

Let's keep the ability to have email notifications in mind, but skip its implementation for now

**Comment by k-gregory** [comment]
http://zakon5.rada.gov.ua/laws/show/z1568-15#n21
> Доступ користувачів до реєстрів здійснюється після навчання їх роботі з такими реєстрами та за умови використання електронного цифрового підпису, що відповідає вимогам, передбаченим Законом України "Про електронний цифровий підпис", та є сумісним з програмним забезпеченням реєстрів.
> Користувач самостійно здійснює дії, пов’язані з отриманням електронного цифрового підпису в Акредитованому центрі сертифікації ключів.
