### ISSUE TITLE
Add swagger docs

### ISSUE THREAD

**Issue by kostya9** [k-gregory/registry#8]
The requirement to test REST API is quite frequent. To make that simplier, we could use swagger ui,

http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

Instead of typing urls, you could just push a button under the specific controller and action

**Comment by k-gregory** [comment]
Fixed in 3223ae060ccf300e0e387f7c95ddc226ce22ebd4
Swagger UI is at https://gregory-k.me/swagger-ui.html

**Comment by k-gregory** [comment]
However the host used by Swagger UI seems to be incorrect. It uses http://localhost:8080/api/... but API is available at https://gregory-k.me/api/...

**Comment by k-gregory** [comment]
Fixed in ba2aac1ed46939de4c1e25dc257a4667aee0e7ee
